### ISSUE TITLE
App crash (pick image/images from GDrive without Crop option)

### ISSUE THREAD

**Issue by scijoker** [miguelbcr/RxPaparazzo#28] opened 2016-07-07 05:47 UTC
App crash after pick images from Google Drive (or any remote storage) without cropping
Logs:
`  java.lang.RuntimeException: Unable to destroy activity {com.fuck_boilerplate.rx_paparazzo.sample/rx_activity_result.HolderActivity}: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                              at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
                                                                                              at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
                                                                                              at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                           Caused by: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                              at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
                                                                                              at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
                                                                                              at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                                              at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                                                                                              at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                                              at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
                                                                                              at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:143)
                                                                                              at rx.internal.operators.OperatorMap$MapSubscriber.onError(OperatorMap.java:85)
                                                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
                                                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:810)
                                                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:571)
                                                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
                                                                                              at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:844)
                                                                                              at rx.observers.Subscribers$5.onError(Subscribers.java:224)
                                                                                              at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:192)
                                                                                              at rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:269)
                                                                                              at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:335)
                                                                                              at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
                                                                                              at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:268)
                                                                                              at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                                              at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
                                                                                              at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:79)
                                                                                              at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:75)
                                                                                              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                                              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                                              at rx.Observable.unsafeSubscribe(Observable.java:8460)
                                                                                              at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:214)
                                                                                              at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:156)
                                                                                              at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:122)
                                                                                              at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:268)
                                                                                              at rx.Subscriber.setProducer(Subscriber.java:209)
                                                                                              at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:79)
                                                                                              at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:75)
                                                                                              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                                              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                                          	at rx.Observable.unsafe
`

**Comment by miguelbcr** [comment] 2016-07-07 13:37
Thanks @scijoker !
we are working on it.

**Comment by miguelbcr** [comment] 2016-07-11 11:07
Hi @scijoker 
We've released [version 0.1.8](https://github.com/FuckBoilerplate/RxPaparazzo/releases/tag/0.1.8) that fixes it.

Try it out and let us know if it works.
Thanks!

**Comment by miguelbcr** [comment] 2016-07-15 13:13
I'm going to close it due to lack of interaction.
Feel free to open it.

**Comment by sagartrehan** [comment] 2016-08-23 05:03
Getting following crash again and again:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.smallcircles/rx_activity_result.HolderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'rx_activity_result.OnResult rx_activity_result.Request.onResult()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'rx_activity_result.OnResult rx_activity_result.Request.onResult()' on a null object reference
       at rx_activity_result.HolderActivity.onCreate(HolderActivity.java:33)
       at android.app.Activity.performCreate(Activity.java:6245)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)


Using 0.2.0 version of library

**Comment by miguelbcr** [comment] 2016-08-23 06:44
Hi @sagartrehan !
Are you using sample app? 
If yes, tell me in which option do you get the error. 
If not, copy your code here.

Also I'll need Android version and device model to try get a close scenario to reproduce the bug because I wasn't capable to reproduce it.

**Comment by sagartrehan** [comment] 2016-08-23 08:55
@miguelbcr 

Sure I will share all details once I reached home. Thanks for the Support :)

**Comment by sagartrehan** [comment] 2016-08-25 15:41
Hi @miguelbcr 

Following crash is not getting reproduced on my device. But it's reproducing constantly on device that tester is using. I am not having access to his device.

I forward him sample app and it is working properly on his device without any crash!

I am using following codebase for capturing image from camera or gallery:

```
// region select profile thumb
    public void takeImage(boolean shouldTakeUsingCamera) {
        try {
            UCrop.Options options = new UCrop.Options();
            options.setHideBottomControls(true);

            RxPaparazzo.BuilderImage<ProfileFragment> imageRxBuilder = RxPaparazzo
                .takeImage(this)
                .useInternalStorage()
                .size(Size.Small)
                .crop(options);

            if (shouldTakeUsingCamera) {
                imageRxBuilder.usingCamera()
                    .subscribe(createProfileSelectedSubscriber());
            } else {
                imageRxBuilder.usingGallery()
                    .subscribe(createProfileSelectedSubscriber());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private Subscriber<Response<ProfileFragment, String>> createProfileSelectedSubscriber() {
        return new Subscriber<Response<ProfileFragment, String>>() {
            @Override
            public void onCompleted() {

            }

            @Override
            public void onError(Throwable e) {

            }

            @Override
            public void onNext(Response<ProfileFragment, String> response) {
                try {
                    if (response.resultCode() != Activity.RESULT_OK) {
                        return;
                    }
                    response.targetUI().loadProfileImage(response.data());
                } catch (Exception ex) {
                    // TODO: Sorry for doing this. This will get removed soon
                }
            }
        };
    }

    private void loadProfileImage(String filePath) {
        ImageUtil.setImageFromFileAbsolutePath(filePath, mProfileThumb, ImageUtil.PROFILE);
        getView().findViewById(R.id.profile_progress_bar).setVisibility(View.VISIBLE);
        getOps().uploadProfilePic(filePath);
	}
// endregion
```

I tried catching exception but it didn't work. Since the exception is producing in HolderActivity class.

Device Details on which crash is reproducing:
Device Model: Motorola G-2
OS: Android 6.0

Please let me know if I am doing something wrong.

**Comment by miguelbcr** [comment] 2016-08-26 06:57
Hi @sagartrehan,
I've not tested your code but it looks right. Only 3 things:

- The try-catch can be removed because probably it will be thrown on your `Subscriber.onError()` method, where you can put `e.printStackTrace()` .Only the `catch` will be reached if your `loadProfileImage()` crashes.

- Remove `.crop(options)` and try again.

- Does the sample app work fine on  Motorola G-2 - 6.0?

**Comment by sagartrehan** [comment] 2016-08-30 04:29
Hi @miguelbcr 

1. I agree with your first point I have removed try catch block from code.
2. Crash is not occurring on my device but on tester device. I shared a build with him by removing .`crop(options)`. I will let you know once I get feedback from him.
3. Yes sample app works properly for him on Motorola G-2 6.0.

Thanks

**Comment by sagartrehan** [comment] 2016-08-31 07:21
Hi @miguelbcr 

I shared build with tester by disabling the crop options and now he is not getting any crash. So the issue is with crop option only. Since this crash is not reproducing on all devices so let me know if I can add a particular hack to fix the issue, since I have no other option as of now.

**Comment by miguelbcr** [comment] 2016-08-31 08:01
I think it's related with the crop options but I'm not sure, so try to use .crop() instead .crop(options) and let me know if it still works.
Anyway I'll take a look this weekend or next week.

**Comment by sagartrehan** [comment] 2016-08-31 10:25
Thanks @miguelbcr, I will try by removing the options from crop(option) and let you know know.

**Comment by miguelbcr** [comment] 2016-09-03 12:10
Hi @sagartrehan !
I've released [version 0.2.2](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.2.2)
I've updated gradle libraries, exactly [RxActivityResult version](https://github.com/VictorAlbertos/RxActivityResult/releases/tag/0.3.5), which could be related with this crash.

Try it out and let me know if it works, Also you could try to use crop options

**Comment by sagartrehan** [comment] 2016-09-04 13:07
Thanks @miguelbcr I have updated the library. I will let you know once I get response from tester.

**Comment by sagartrehan** [comment] 2016-09-07 17:11
Thanks @migulelbcr crash is fixes now. Issue is not getting reproduced. Thanks for help.

**Comment by miguelbcr** [comment] 2016-09-07 17:18
I'm glad to hear that ;)
You can try the [version 0.2.6](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.2.6) out. 
That version fixes some issues and also works on API 24 (Android 7)

**Closed by miguelbcr** 2016-09-07 17:18 UTC

**Comment by sagartrehan** [comment] 2016-09-08 06:29
Sure I will update the library version. Thank you
